# Generated by Django 2.2 on 2019-04-23 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_register2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('msg', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact1',
        ),
    ]
