# Generated by Django 2.2 on 2019-04-23 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20190423_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact3',
            old_name='fname',
            new_name='a',
        ),
        migrations.RenameField(
            model_name='contact3',
            old_name='lname',
            new_name='b',
        ),
        migrations.RenameField(
            model_name='contact3',
            old_name='msg',
            new_name='c',
        ),
    ]
