# Generated by Django 2.2 on 2019-04-23 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20190423_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact3',
            old_name='a',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contact3',
            old_name='b',
            new_name='msg',
        ),
        migrations.RenameField(
            model_name='contact3',
            old_name='c',
            new_name='name',
        ),
    ]
