# Generated by Django 2.2 on 2019-04-29 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_auto_20190423_1128'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register2',
            new_name='Register4',
        ),
    ]
