# Generated by Django 2.2 on 2019-04-30 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_auto_20190429_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='R4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('no', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('seats', models.CharField(max_length=100)),
                ('charges', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('pwd', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='pgpics/')),
            ],
        ),
    ]
