# Generated by Django 2.2 on 2019-04-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_feed2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registerpg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hno', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('land', models.CharField(max_length=100)),
                ('seats', models.CharField(max_length=100)),
                ('room', models.CharField(max_length=100)),
                ('food', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='pgpics/')),
            ],
        ),
        migrations.DeleteModel(
            name='R4',
        ),
    ]
