# Generated by Django 2.2 on 2019-05-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_auto_20190430_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applypg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=100)),
                ('hno', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('seats', models.CharField(max_length=100)),
                ('fname', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('no', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='pgpics/')),
            ],
        ),
    ]
