# Generated by Django 2.2 on 2019-05-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_applypg'),
    ]

    operations = [
        migrations.AddField(
            model_name='applypg',
            name='email',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
