# Generated by Django 2.2 on 2019-05-03 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_applypg_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sendreq1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('no', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('type', models.ImageField(upload_to='pgpics/')),
                ('msg', models.CharField(max_length=100)),
            ],
        ),
    ]
