# Generated by Django 2.2 on 2019-05-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_sendreq1'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendreq1',
            name='p_email',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sendreq1',
            name='p_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sendreq1',
            name='rpy',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sendreq1',
            name='msg',
            field=models.CharField(max_length=500),
        ),
    ]
